### ISSUE TITLE
Optional - please consider add "Alternative names" to cards

### ISSUE THREAD

**Issue by DevGlogicM** [AlanOC91/YGOPRODeck#11]
While I was searching for missing cards in the archetypes, I found the card called [Abyss Actor - Trendy Understudy](https://db.ygoprodeck.com/card/?search=Abyss%20Actor%20-%20Trendy%20Understudy), but, the card image in YGOPRODeck website has other name.

While a solution could be update the card image, I really don't know the erratas or re-printings and its changes, honeslty.

It would be helpful if cards has a section or a visible way to users see the alternative names cards could have.

**Comment by AlanOC91** [comment]
The card name on the artwork is the beta name of the card in this case.

When the card is first revealed and translated to English (unofficially) it's given a beta name.

When it's officially released the official name is given then. 

I'll have to update a couple of card images to reflect this.

My database does hold these beta names most of the time though. This is usually to preserve card tooltips on the main website.

If you search "abyss - actor dandy supporting actor" it'll give you the same result.

I'm not sure about showing the beta name on the front end since it's no longer relevant when the official name is released.

Best solution is to update card artwork with official name. 

I'll work on doing a card artwork pass and do a mass update on them.

**Comment by AlanOC91** [comment]
9k card arts updated today. Many card names fixed to use official name now.

Optimized all cards for the web, reducing their size without losing quality which should result in lower bandwidth and higher speeds.

Will do another card art run Jan/Feb 2019.
