### ISSUE TITLE
API: Searching by card id does not seem to work in name

### ISSUE THREAD

**Issue by rerpha** [AlanOC91/YGOPRODeck#130]
I tried using this command: 
`api/v5/cardinfo.php?name=64509569` 

to look up a chimeratech overdragon and it didn't seem to work, nor did any other ID commands. Am i misusing the api or is this a bug? 

If I am misusing it, could an example of how to use the ID be added to the docs? thanks

**Comment by AlanOC91** [comment]
Hey there,

We don't have a card which has an ID of `64509569` which is why you are getting an invalid response. 

Chimeraech Overdragon has an ID of `64599569` which does work:

`https://db.ygoprodeck.com/api/v5/cardinfo.php?name=64599569`

Where did you get that ID? 

ID references:
https://db.ygoprodeck.com/card/?search=Chimeratech%20Overdragon
https://yugipedia.com/wiki/Chimeratech_Overdragon

**Comment by rerpha** [comment]
> 
> 
> Hey there,
> 
> We don't have a card which has an ID of `64509569` which is why you are getting an invalid response.
> 
> Chimeraech Overdragon has an ID of `64599569` which does work:
> 
> `https://db.ygoprodeck.com/api/v5/cardinfo.php?name=64599569`
> 
> Where did you get that ID?
> 
> ID references:
> https://db.ygoprodeck.com/card/?search=Chimeratech%20Overdragon
> https://yugipedia.com/wiki/Chimeratech_Overdragon

sorry, was my own fault, it was a typo. Cheers for such a quick response!

**Comment by AlanOC91** [comment]
No problem! Any other problems then feel free to open a new issue.
