### ISSUE TITLE
Add a "No cards found" in the "search cards" field

### ISSUE THREAD

**Issue by DevGlogicM** [AlanOC91/YGOPRODeck#15]
In the "Search cards" field, if you type a card name, it shows "related results" that matched with the input.

Example: if you type "Guardian", you'll get these results:

_Click to enlarge the image:_
![you will get this results](https://user-images.githubusercontent.com/17280493/43536812-2f77ab82-9583-11e8-96b1-c247e8883df5.png)

But, _(if it doesn't get any results)_, no message is shown.

My suggestion is: 

- If no results are found, please show a message like this one:

```
No cards results found with "typed_text" name or lore on it.
Press ENTER key for generate an advanced search.

```

**Comment by AlanOC91** [comment]
Investigating this further from a user perspective. 

Sites like [Scryfall ](https://scryfall.com/) and [Hearthpwn ](https://www.hearthpwn.com) don't seem to utilize methods like this but none of them seem to be using any form of auto-complete either. 

Worried that a user will see error and immediately give up without fully reading the error.

On the flip-side, a user may be waiting for an auto-complete that never shows up because of the lack of a message.

**Comment by AlanOC91** [comment]
This is potentially defunct now thanks to #82 with Fuzzy Searching.

Also, other databases don't seem to do this so unsure if it's even a viable addition now.
