### ISSUE TITLE
Card with "?" ATK/DEF

### ISSUE THREAD

**Issue by orozso** [AlanOC91/YGOPRODeck#152]
Some card's ATK and DEF is "?", but this in the database/api "0".

Tip: Special value for "?" (e.g.: -1 (minus one))

e.g.: `Slifer the Sky Dragon`

**Comment by AlanOC91** [comment]
I've been reluctant to do this for quite some time for a couple of reasons:

- Changing it could cause issues for those using the API in calculations
- I'm generally not a fan of storing negative integer values

I'll look into it a bit more but it's going to be an issue especially on an API level. If I store them as -1 and make -1 show as "?" in the API then this could cause issues for everyone using the API that are expecting an integer value.

**Comment by mvettosi** [comment]
You could add two new fields, for example:
{"is_atk_undefined": true/false, "is_def_undefined": true/false}
This way you should not break anything existing, and still giving the api users a way to display it correctly

**Comment by CAS-ual-TY** [comment]
Imo going for a negative integer here is the goto solution. It seems to be better than an extra field. Personally, I would not do this in v7, however, and rather do it in the next version (v8?) to make sure nothing is broken, because of - as you said - the calculators that use it.  
When it comes to calculating, then a "?" has to be handled in a special way, anyways. Once the calculators would move on to the next theoretical version, then they could decide themselves how to do it and even just continue to handle "?" as a "0", if they want to.  
Another solution I could think of is a request flag. Something like &showSpecialValues or similar, which you need to add to your request to indicate that you want these special values shown. Pre-existing API users would not be broken that way.

**Comment by CAS-ual-TY** [comment]
@AlanOC91 bumping this if you dont mind

**Comment by AlanOC91** [comment]
Using `&misc=yes` will now show `question_atk` and/or `question_def` to be `1` for true if a card is found to have a `?` in the data.
