### ISSUE TITLE
Card Collection Export Special character Bug

### ISSUE THREAD

**Issue by PackSciences** [AlanOC91/YGOPRODeck#157]
Hello,

The 11th of April, I reported to the team a bug about the export to .csv of the card collection function. At first, I believed it was a problem of the length of this export. But then I figured out it wasn't the problem. I believe the problem occurs when a card has the character "#" in its name (Samurai Sasuke #4 in my case) which stops the writing of the csv file.

Example in my collection exported to .csv:

`"Sangan",1,26202165,"Common","M","Unlimited","Legendary Decks II","LDK2-ENY21"
"Sasuke Samurai `

and the file stops there.

**Comment by AlanOC91** [comment]
Thanks for the detailed bug report! This issue has now been fixed. You may need to refresh your web browser cache to get the latest files (you can also do ctrl + f5).

Note to self: [encodeURIComponent](https://www.w3schools.com/jsref/jsref_encodeuricomponent.asp) instead of [encodeURI.](https://www.w3schools.com/jsref/jsref_encodeuri.asp)
