### ISSUE TITLE
Card ID changing

### ISSUE THREAD

**Issue by NoahReyson** [AlanOC91/YGOPRODeck#158]
Hi, me again,

I noticed the ID of some recent cards changed over time.
For example "Bastard the Ashen Dragon" went from 101101038 to 41373230, causing a duplicate in my local database.

Which seems all the more strange when the ID on the card (see https://storage.googleapis.com/ygoprodeck.com/pics/41373230.jpg) is 101101038.

I would like to know what is this sorcery in order to adapt myself to the best of my side.
(Especially if the ID is not the primary key of your database)

Thank you.

**Comment by AlanOC91** [comment]
Hey there,

Allow me to explain, when an ID is over 10000000 it means that the ID is a beta/unofficial ID. This is done because for newly revealed cards, the official Card ID/Passcode is not revealed. When it's eventually revealed, the ID is then update to line up with the official reveal. 

We have the following endpoints to track these changes:

https://db.ygoprodeck.com/api/v7/changelogID.php
https://db.ygoprodeck.com/api/v7/changelogName.php

**Comment by NoahReyson** [comment]
Ok.

I have two more questions  : 
1) Does changelogID cover all cards that have changed (the file is never reset? Some information is not deleted after a certain time?)
2) Can two cards have the same temporary ID? Not at the same time of course, but can a temporary ID be reused?

Thanks

**Comment by AlanOC91** [comment]
- ChangelogID isn't changed. The only time I delete records from it is when an ID was changed by mistake (wrongly inserted and then changed for example) which would cause it to appear. 
- IDs are never reused. Beta IDs are never reused. In fact you can still search them, we have full 
backwards compatibility for that. 

https://db.ygoprodeck.com/api/v7/cardinfo.php?id=101101038
