### ISSUE TITLE
[Suggestion] Request parameter "format" of "Get Card Information" endpoint contains space

### ISSUE THREAD

**Issue by Doarakko** [AlanOC91/YGOPRODeck#180]
Spaces are URL encoded.
API users don't have to worry about a few things if you avoid using space.
Could you change it to a snake case?

format
- goat
- ocg goat
    - ocg_goat
- speed duel
    - speed_duel
- rush duel
    - rush_duel
- duel links
    - duel_duel

**Comment by AlanOC91** [comment]
We currently only use snake case for the parameter itself rather than the value returned.

While I agree it would potentially be easier, that would lead to a lot of inconsistencies in the API. If I changed that, I would have to change the rest of the data to snake case such as "normal_monster" for card types, "Ultra_Rare" for rarities and "allure_queen" for archetype.

I won't be changing any of these anytime soon but it's a potential idea for future revisions of the API. Maybe I can add it as an API option.
