### ISSUE TITLE
API: Some Rush Duels cards are missing important information

### ISSUE THREAD

**Issue by smith-ross** [AlanOC91/YGOPRODeck#266]
When trying to generate a list of all Rush Duel cards, alongside their associated effects, I noticed that some (but still a very significant amount) of the Rush cards were missing their effect requirements, alongside the [Requirement] and [Effect] tags, in their description. This is detrimental as I'd prefer not having to manually input each of these considering the volume if avoidable.

Example of a messed up one:
[Antbellion of the Rebellion](https://db.ygoprodeck.com/api/v7/cardinfo.php?format=rush%20duel&id=160004033)

Example of a correct one:
[Agent Telepath](https://db.ygoprodeck.com/api/v7/cardinfo.php?format=rush%20duel&id=160201030)

You'll notice that Agent Telepath features both the Requirement and Effect, while Antbellion of the Rebellion features only the effect, and it is not tagged with [Effect] either

**Comment by AlanOC91** [comment]
Hi there,

I've identified the issue in my script that was causing it to ignore the [REQUIREMENT] effect. It's in some of the earlier cards due to them being entered in manually.

The script itself is now fixed (I've tested by inserting ~20 new Rush cards) and I'm going to go back through every Rush card and have their description updated since the formatting on some of the older ones are different.

**Comment by AlanOC91** [comment]
I've ran my script through all 400+ Rush Cards in our Database and they should all be updated to use the same description syntax along with including [REQUIREMENT] where it was missing.

Thanks!
