### ISSUE TITLE
Predaplant Ophrys Scorpio is a common instead of a rare in Maximum Crisis in the pack opener

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#307]
In [this video](https://youtu.be/C8M_uSsaxvg?t=605) (Timestamp is at 10:05 in case the link is not working) of a Maximum Crisis opening a Predaplant Ophrys Scorpio is pulled as a common even though it should be a rare.

I could replicate this as I was writing this issue.

The rarity is wrong on the set breakdown as well. Is it maybe related with TCGPlayer having the wrong rarity?

* https://db.ygoprodeck.com/set-breakdown/
* https://www.tcgplayer.com/product/131126/yugioh-maximum-crisis-predaplant-ophrys-scorpio?partner=YGOPRODeck&utm_campaign=affiliate&utm_medium=set-breakdown&utm_source=YGOPRODeck&Language=English

The API has the correct rarity btw: https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Predaplant%20Ophrys%20Scorpio

**Comment by AlanOC91** [comment]
Thanks for reporting this! It's most definitely because TCGplayer has it listed as common as we use this data, particularly for the pack opening simulator (and the set breakdown page).

We don't use our own set of data for it. At the time this was due to constraints in the way we handled set data. Since then, we have massively improved the flow of how we handle our own data but it would require a bit of a re-work on the pack simulator to move over (this is planned).

In the meantime, I'll report the issue to TCGplayer. They are usually good for fixing these issues.
