### ISSUE TITLE
Issues with releases of Frostosaurus, Mask of Darkness, Igknight Gallant and Tokens in OTS Packs

### ISSUE THREAD

**Issue by larikk** [AlanOC91/YGOPRODeck#334]
I ran my validation scripts for Battle Packs, Reprint Packs and all of the flavours of Tournament Packs. Here is what I found.

Frostosaurus in Battle Pack 2 is listed as Common and Mosaic Rare but it should be Rare and Mosaic Rare instead.
https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Frostosaurus

Mask of Darkness in Dark Legends is listed as Common and Rare but it should be only Rare.
https://db.ygoprodeck.com/api/v7/cardinfo.php?name=Mask%20of%20Darkness

Igknight Gallant in Astral Pack Eight is listed as Common and Super Rare but it should be only Super Rare.
https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Igknight%20Gallant

----

Last point is not really something wrong but more of an inconsistency: Since OTS Pack 8 the packs can have a token card. Some of the packs in the API have this card included while others do not.

With token:
```
8: Sky Strike Ace Token
9: Mecha Phantom Beast Token
15: World Legacy Token
```

Without token:
```
10: Trickstar Token
11: Duel Dragon Token
12: Primal Being Token
13: Generaider Token
14: Dual Avatar Spirit Token
17: Ice Barrier Token
```

I'm not sure about 16. I think that one had no token.

The token stuff applies to the card search as well:
* https://db.ygoprodeck.com/set/?search=OTS%20Tournament%20Pack%208 has the token
* https://db.ygoprodeck.com/set/?search=OTS%20Tournament%20Pack%2010 does not

I have no opinion on whether they should be included or not but it should be consistent I think.

**Comment by AlanOC91** [comment]
The First 3 cards you mentioned are fixed.

I know what the issue with the Tokens is. When querying the API it does a join with our main card database. If it doesn't find a card it's excluded. This normally isn't an issue but we actually have very few tokens in our main card database which is why you are finding missing ones. I can look into getting them added but it's a slightly low priority at the moment. I'll open a new issue for it. 

#335
