### ISSUE TITLE
Actual Monster Typings

### ISSUE THREAD

**Issue by oshinowo-stephen** [AlanOC91/YGOPRODeck#341]
Using the API made me notice the typings of monster's seemed a bit off... for example, when I get to the extra deck range of monsters it seems like "Normal" and "Effect" monsters weren't really handled properly for example: cards such as Sea Monster of Theseus is handled as "Fusion" monster and that's it when in reality it's a "Fusion Tuner" and other fusion monsters such as: Red-Eyes Slash Dragon and all other Effect Fusion Monsters are still treated as "Fusion" Monsters when in reality they're "Fusion Effect" or "Fusion Normal"... still a range more typings such "Ritual Tuner" and "Fusion Tuner Effect" all of that is still not being handled properly... sorry to disturb but it'll be appreciated if y'all looked into it 😄

**Comment by whoastonic** [comment]
Using the API made me notice the typings of monster's seemed a bit off... for example, when I get to the extra deck range of monsters it seems like "Normal" and "Effect" monsters weren't really handled properly for example: cards such as **Sea Monster of Theseus** is handled as "Fusion" monster and that's it when in reality it's a "Fusion Tuner" and other fusion monsters such as: **Red-Eyes Slash Dragon** and all other Effect Fusion Monsters are still treated as "Fusion" Monsters when in reality they're "Fusion Effect" or "Fusion Normal"... still a range more typings such "Ritual Tuner" and "Fusion Tuner Effect" all of that is still not being handled properly... sorry to disturb but it'll be appreciated if y'all looked into it 😄

**Comment by NARFNra** [comment]
https://github.com/AlanOC91/YGOPRODeck/issues/295 I believe this issue is about the same thing, and has specific incidents of the affected cards.

It's worth noting, though, that there's no such thing as a Fusion/Normal card - formally cards like Mavelus are not considered Normal Monsters, and effects that refer to them refer to them instead as "Non-Effect" monsters. So it might be better to say the problem is lack of "Fusion/Effect"'s existence - which should be the typing for cards that aren't Non-Effect ones.

**Comment by oshinowo-stephen** [comment]
honestly I forgot i made this, but no you do have a point while working with the API more and more I've came to the understanding that it's not really worth doing something like it, for effect/non-effect monsters since `has_effect` is a thing *unsure exactly when this was implemented* but thank-you for the response
