### ISSUE TITLE
Downloader ended

### ISSUE THREAD

**Issue by AlexsanderRST** [AlanOC91/YGOPRODeck#367]
Hello again. I decided to terminate the project. There was a couple of solutions to the second point, but I understood the first and it's not fair to continue with this program.

**Comment by AlanOC91** [comment]
Hey there!
I really really appreciate how you've handled this situation. You could have easily gone a different way with this so you have my sincerest gratitude for this. I'm sorry to have to come to you with the request because it was a nice tool but I'm very glad you understood my points. 

Thanks so much again.
