### ISSUE TITLE
relationship in card_id vs set_code and image

### ISSUE THREAD

**Issue by wnunezc** [AlanOC91/YGOPRODeck#440]
I have created my local database to then copy the information of the cards, the sets in which they were printed and the images related to each image id, i am using this request:

https://db.ygoprodeck.com/api/v7/cardinfo.php

and the following happens:

when i perform a search based on set_code of the card: **MP22-EN266**
get the card id: **89631139**

When I try to go through the url of the image, it returns **_8 images related_** to the card id **89631139**
and not all these images belong to the print set.

¿How can I obtain the image exclusively of the art that corresponds to the printing set?

Other problems, I think it is that the name of the image is not complete, I mean that it is returned without the leading zeros.

**Comment by AlanOC91** [comment]
This was answered in the discord server but for anyone else:

Our images are generated renders of a card. So for example, we have 1 image of Time Wizard rendered that is associated with it's card ID. We don't store images via Set Code.

Usually, when someone wants this, it's because they are trying to use these renders for some sort of storefront. If this is your intention, I must state that we absolutely do not recommend using card renders to attempt to associate with real card images for a sale.

**Comment by wnunezc** [comment]
and you recomended use tcgplayer image for storefront ...
