### ISSUE TITLE
Missing pack "25th Anniversary Ultimate Kaiba Set"

### ISSUE THREAD

**Issue by metallicity** [AlanOC91/YGOPRODeck#486]
The "25th Anniversary Ultimate Kaiba Set" released back in the beginning of March, containing mostly reprints, but also three new (to TCG) cards, "Grappler", "Life Shaver", and "Magical Trick Mirror". As the set is entirely absent from YGOPRODeck (minus a link to TCGPlayer which knows about the TCG printing), these cards are not marked as TCG legal and lack a TCG release date.

This seems to be a recurring issue with new products, to the point where I simply don't trust YGOPRODeck to accurately reflect TCG cards released within the last few months.

**Comment by AlanOC91** [comment]
We use Yugipedia to pull set into automatically, primarily through their "categories" for the card sets. 

https://yugipedia.com/wiki/Category:TCG_sets

We query each category and look for new sets and then add the sets and the card list to our internal database. These categories almost never change and most sets fall under the categories in the list above.

It seems like "25th Anniversary Ultimate Kaiba Set" is an exception to this and was added as it's own unique category which seems odd. It really looks like it should have been filed under "TCG promotional cards". 

Anyway, that's why it wasn't picked up. I went ahead and added the above to our list and it should be picked up in the next card set run in a handful of hours. 

Thanks for reporting.
