### ISSUE TITLE
Change color of saved card once added in the localStorage-Saved Database cards

### ISSUE THREAD

**Issue by DevGlogicM** [AlanOC91/YGOPRODeck#94]
When a card is added to the "Saved Database cards"-localStorage, the "Save Card" button color is not changed - it only shows its color change when the page is reloaded.

Example: 

- Enter to this URL for add the card called ["Contract with the Abyss"](https://db.ygoprodeck.com/card/?search=Contract%20with%20the%20Abyss).

- Press "Save Card" button.

- Color is not changed-reload the page.

Optional: it _could_ be useful if the text of the button changes - if the card was saved, it should say: _"Saved Card"_.

Thanks.

**Comment by AlanOC91** [comment]
Hmm this doesn't seem to be correct. Because the button SHOULD change color if the card is saved.

Example:

- I visit the card.
- I hit save.
- I reload the page.

Then:
http://imgur.com/gallery/BbtIRix

This was an issue but it was fixed on #92. If it's still not working for you, please clear your web browser cache and re-test. If it's not working after that, please let me know what web browser and device you are using.

Thanks!

**Comment by DevGlogicM** [comment]
I'm using Google Chrome - Desktop
Version 76.0.3809.132 (Build oficial) (32 bits)

After reloading the page, the result is correct - [see image sample](https://imgur.com/oN2bl8c).
Indeed, it was a cache-related problem.

I wasn't clear before that I use the "dark theme" instead the "light theme" you use in your example, It might be worth check the "dark theme" - in the "light theme" is clear when you save a card, the button color changes, but it is not clear at first glance in the "dark theme".

> This is more a opinion, though, but, users shouldn't reload the page for see the changes made on it.

Thanks :)

**Comment by AlanOC91** [comment]
Saved cards in Night Mode have now been updated to correctly color the button!

![Night Mode](https://user-images.githubusercontent.com/37552458/64946964-ed8c3580-d86b-11e9-9a6a-666013aea61f.png)
